// import Footer from './Footer'
import Head from 'next/head'
// import DynamicNavbar from '../DynamicComps/DynamicNavbar';

const Layout = ({ children }) => {
  return (
    <div className='h-full w-full flex flex-col justify-center items-center overflow-auto scrollbar'>
      <Head>
        <title>Gastos App</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/StammFavicon.svg" /> */}
      </Head>
      {/* <DynamicNavbar /> */}
      <div>
        <main>{children}</main>
      </div>
    </div>
  )
}

export default Layout;