// import Footer from './Footer'
import Head from 'next/head'
import DynamicNavbar from '../DynamicsComps/DynamicNavbar';

const Layout = ({ children }) => {
  return (
    <div className='h-full w-full min-h-screen overflow-auto scrollbar'>
      <Head>
        <title>Gastos App</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/StammFavicon.svg" /> */}
      </Head>
      <DynamicNavbar />
      <main>{children}</main>
    </div>
  )
}

export default Layout;