// import Footer from './Footer'
import Head from 'next/head'
// import DynamicNavbar from '../DynamicsComps/DynamicNavbar';

const Layout = ({ children }) => {
  return (
    <div className='h-full w-full min-h-screen bg-gray-main'>
      <Head>
        <title>Gastos App</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/StammFavicon.svg" /> */}
      </Head>
      {/* <DynamicNavbar /> */}
      <main className='w-full h-full min-h-screen'>{children}</main>
    </div>
  )
}

export default Layout;